# Deep independent V-L Prompting
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8
  K_TRANSFORMS: 2
  RETURN_IMG0: True

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  #TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  TRANSFORMS: ["randaugment", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 10
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

OPTIM_META:
  NAME: "sgd"
  # LR: 0.002
  # MAX_EPOCH: 10
  # LR_SCHEDULER: "cosine"
  # WARMUP_EPOCH: 1
  # WARMUP_TYPE: "constant"
  # WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 100

TRAINER:
  META:
    PREC: "fp16" 

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"
